name = "archsem-lean"
version = "0.1.0"
defaultTargets = ["ArchSem", "ArchSemTinyArm", "archsem"]

[[require]]
name = "sail_tiny_arm"
git = "https://github.com/rems-project/sail-tiny-arm-lean"
# git = "https://github.com/Chris-F5/sail-tiny-arm"
# rev = "archsem-lean"
# subDir = "lean-snapshot/out"

[[require]]
name = "cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.29.0-rc8"

[[lean_lib]]
name = "ArchSem"
globs = ["ArchSem.**"]

[[lean_lib]]
name = "ArchSemTinyArm"
globs = ["ArchSemTinyArm.**"]

[[lean_exe]]
name = "archsem"
root = "Main"
