name = "archsem-lean"
version = "0.1.0"
defaultTargets = ["ArchsemLean", "ArchSemTinyArm"]

[[require]]
name = "sail_tiny_arm"
# The following lean-snapshot should be built with
# sail: 50d0348da8664342230772ca1647b9eef05f6b7f
# sail-tiny-arm: 8f17b71497fa2e4f8b275194989b6dbbc55dc97e
path = "../sail-tiny-arm/lean-snapshot/out"

[[lean_lib]]
# CR clang for thibaut: Am I supposed to have uppercase 'S' in Archsem?
name = "ArchsemLean"
globs = ["ArchsemLean.**"]

[[lean_lib]]
name = "ArchSemTinyArm"
globs = ["ArchSemTinyArm.**"]

[[lean_exe]]
name = "archsem-lean"
root = "Main"
