arch = "Arm"
name = "R+po+dmb.sy"

[[registers]]
  _PC = 9472
  "R3" = 5376
  "R1" = 1280
  "R0" = 0
  "R2" = 0
  "R4" = 0
  "R5" = 0
  "R6" = 0
  "R7" = 0
  "R8" = 0
  "R9" = 0
  "R10" = 0
  "R11" = 0
  "R12" = 0
  "R13" = 0
  "R14" = 0
  "R15" = 0
  "R16" = 0
  "R17" = 0
  "R18" = 0
  "R19" = 0
  "R20" = 0
  "R21" = 0
  "R22" = 0
  "R23" = 0
  "R24" = 0
  "R25" = 0
  "R26" = 0
  "R27" = 0
  "R28" = 0
  "R29" = 0
  "R30" = 0

[[registers]]
  _PC = 13568
  "R3" = 0
  "R2" = 1280
  "R1" = 5376
  "R0" = 0
  "R4" = 0
  "R5" = 0
  "R6" = 0
  "R7" = 0
  "R8" = 0
  "R9" = 0
  "R10" = 0
  "R11" = 0
  "R12" = 0
  "R13" = 0
  "R14" = 0
  "R15" = 0
  "R16" = 0
  "R17" = 0
  "R18" = 0
  "R19" = 0
  "R20" = 0
  "R21" = 0
  "R22" = 0
  "R23" = 0
  "R24" = 0
  "R25" = 0
  "R26" = 0
  "R27" = 0
  "R28" = 0
  "R29" = 0
  "R30" = 0

[[memory]]
  kind = "code"
  addr = 9472
  step = 4
  data = [3531604000, 4177526816, 3531604002, 4177526882]

[[memory]]
  kind = "code"
  addr = 13568
  step = 4
  data = [3531604032, 4177526816, 3573759935, 4181721155]

[[memory]]
  sym = "x"
  addr = 1280
  step = 8
  data = 0

[[memory]]
  sym = "y"
  addr = 5376
  step = 8
  data = 0

[[termCond]]
  _PC = 9488

[[termCond]]
  _PC = 13584

[[outcome]]
  observable = {"1" = {"R3" = 0}, mem = {y = 2}}
